# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import replicator_pb2 as protos_dot_replicator__pb2


class ReplicatorStub(object):
    """Identification service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.replicate = channel.unary_unary(
                '/Replicator/replicate',
                request_serializer=protos_dot_replicator__pb2.ReplicationRequest.SerializeToString,
                response_deserializer=protos_dot_replicator__pb2.ReplicationReply.FromString,
                )


class ReplicatorServicer(object):
    """Identification service definition
    """

    def replicate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'replicate': grpc.unary_unary_rpc_method_handler(
                    servicer.replicate,
                    request_deserializer=protos_dot_replicator__pb2.ReplicationRequest.FromString,
                    response_serializer=protos_dot_replicator__pb2.ReplicationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Replicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Replicator(object):
    """Identification service definition
    """

    @staticmethod
    def replicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Replicator/replicate',
            protos_dot_replicator__pb2.ReplicationRequest.SerializeToString,
            protos_dot_replicator__pb2.ReplicationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
