# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/replicator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/replicator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17protos/replicator.proto\"%\n\x12ReplicationRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"!\n\x10ReplicationReply\x12\r\n\x05reply\x18\x01 \x01(\t2C\n\nReplicator\x12\x35\n\treplicate\x12\x13.ReplicationRequest\x1a\x11.ReplicationReply\"\x00\x62\x06proto3'
)




_REPLICATIONREQUEST = _descriptor.Descriptor(
  name='ReplicationRequest',
  full_name='ReplicationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='ReplicationRequest.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=64,
)


_REPLICATIONREPLY = _descriptor.Descriptor(
  name='ReplicationReply',
  full_name='ReplicationReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='ReplicationReply.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['ReplicationRequest'] = _REPLICATIONREQUEST
DESCRIPTOR.message_types_by_name['ReplicationReply'] = _REPLICATIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReplicationRequest = _reflection.GeneratedProtocolMessageType('ReplicationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATIONREQUEST,
  '__module__' : 'protos.replicator_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationRequest)
  })
_sym_db.RegisterMessage(ReplicationRequest)

ReplicationReply = _reflection.GeneratedProtocolMessageType('ReplicationReply', (_message.Message,), {
  'DESCRIPTOR' : _REPLICATIONREPLY,
  '__module__' : 'protos.replicator_pb2'
  # @@protoc_insertion_point(class_scope:ReplicationReply)
  })
_sym_db.RegisterMessage(ReplicationReply)



_REPLICATOR = _descriptor.ServiceDescriptor(
  name='Replicator',
  full_name='Replicator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=101,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='replicate',
    full_name='Replicator.replicate',
    index=0,
    containing_service=None,
    input_type=_REPLICATIONREQUEST,
    output_type=_REPLICATIONREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLICATOR)

DESCRIPTOR.services_by_name['Replicator'] = _REPLICATOR

# @@protoc_insertion_point(module_scope)
